metachecker/routes/collection.py
from math import ceil

from flask import Blueprint, render_template, flash
from flask import request, redirect, url_for
from flask_login import current_user
from web3.auto import w3

from metachecker.models import Collection, User, Token, Access
from metachecker.tasks.metadata import fetch_collection_metadata
from metachecker.factory import db
from metachecker import config


bp = Blueprint('collection', 'collection')


@bp.route('/')
def index():
    if current_user.is_anonymous:
        collections = None
    else:
        collections = Collection.query.filter().order_by(Collection.create_date.desc()).all()
        collections = [i for i in collections if i.user_can_access(current_user.id)]
    return render_template('index.html', collections=collections)


@bp.route('/new', methods=['GET', 'POST'])
def new():
    if not current_user.is_authenticated:
        flash('You need to connect your wallet first.', 'warning')
        return redirect(url_for('collection.index'))
    if not current_user.is_admin:
        flash('You are not able to add new collections.', 'warning')
        return redirect(url_for('collection.index'))
    if request.method == 'POST':
        if not request.form.get('title'):
            flash('You need to specify a collection title.', 'warning')
            return redirect(url_for('collection.new'))
        if not request.form.get('metadata_uri').startswith('http'):
            flash('You need to specify a proper base metadata URI, ie, https://gateway.pinata.cloud/ipfs/xxxxxxxxxxx/', 'warning')
            return redirect(url_for('collection.new'))
        if not request.form.get('start_token_id').isnumeric():
            flash('You need to specify a valid starting token number, ie, 0 or 1', 'warning')
            return redirect(url_for('collection.new'))
        if not request.form.get('end_token_id').isnumeric():
            flash('You need to specify a valid ending token number, ie, 7777,10000,etc', 'warning')
            return redirect(url_for('collection.new'))
        metadata_uri = request.form.get('metadata_uri')
        if not metadata_uri.endswith('/'):
            metadata_uri = metadata_uri + '/'
        c = Collection(
            title=request.form.get('title'),
            metadata_uri=metadata_uri,
            start_token_id=request.form.get('start_token_id'),
            end_token_id=request.form.get('end_token_id'),
            user_id=current_user.id
        )
        db.session.add(c)
        db.session.commit()
        fetch_collection_metadata.schedule([c.id], delay=3)
        return redirect(url_for('collection.show', collection_id=c.id))
    return render_template(
        'new.html'
    )


@bp.route('/collection/<collection_id>')
def show(collection_id):
    collection = Collection.query.filter(Collection.id == collection_id).first()
    if not collection:
        flash('That collection does not exist!', 'warning')
        return redirect(url_for('collection.index'))
    if current_user.is_anonymous:
        flash('Must be authenticated.', 'warning')
        return redirect(url_for('collection.index'))
    if not collection.user_can_access(current_user.id):
        flash('You are not allowed to access that collection.', 'warning')
        return redirect(url_for('collection.index'))
    # Determine which batch of tokens to preview
    start = collection.start_token_id
    _start = request.args.get('start')
    if _start and _start.isnumeric():
        start = _start
    start = int(start)
    return render_template(
        'collection.html',
        collection=collection,
        start=int(start),
        end=int(start + 16)
    )

@bp.route('/collection/<collection_id>/add_collaborator')
def add_collaborator(collection_id):
    collection = Collection.query.filter(Collection.id == collection_id).first()
    if not collection:
        flash('That collection does not exist!', 'warning')
        return redirect(url_for('collection.index'))
    if current_user.is_anonymous:
        flash('Must be authenticated.', 'warning')
        return redirect(url_for('collection.show', collection_id=collection.id))
    if not collection.user_id == current_user.id:
        flash('Must be the owner of the collection to add collaborators.', 'warning')
        return redirect(url_for('collection.show', collection_id=collection.id))
    address = request.args.get('address')
    if address:
        address = address.lower()
        if w3.isAddress(address):
            if collection.user.public_address == address:
                flash('Cannot add that collaborator, they own the collection.', 'warning')
            else:
                exists = Access.query.filter(Access.public_address == address).first()
                if exists:
                    flash('Collaborator already added.', 'warning')
                else:
                    a = Access(
                        public_address=address,
                        collection_id=collection.id
                    )
                    db.session.add(a)
                    db.session.commit()
                    flash(f'Collaborator {address} added!', 'success')
        else:
            flash('Invalid ETH address provided.', 'error')
    return redirect(url_for('collection.show', collection_id=collection.id))

@bp.route('/collection/<collection_id>/<token_id>')
def show_token(collection_id, token_id):
    prev, next = None, None
    collection = Collection.query.get(collection_id)
    if not collection:
        flash('That collection does not exist!', 'warning')
        return redirect(url_for('collection.index'))
    token = Token.query.filter(
        Token.token_id == token_id,
        Token.collection_id == collection_id
    ).first()
    if not token:
        flash('That token does not exist for that collection!', 'warning')
        return redirect(url_for('collection.show', collection_id=collection_id))
    if current_user.is_anonymous:
        flash('Must be authenticated.', 'warning')
        return redirect(url_for('collection.index'))
    if not collection.user_can_access(current_user.id):
        flash('You are not allowed to access that collection.', 'warning')
        return redirect(url_for('collection.index'))

    _show = request.args.get('show')
    rejected, approved, all = False, False, False
    if _show == 'rejected':
        rejected = True
    elif _show == 'approved':
        approved = True
    else:
        all = True
    tokens = collection.get_tokens(rejected=rejected, approved=approved, all=all).all()
    index = tokens.index(token)
    if index + 1 < len(tokens):
        next = tokens[index + 1]
    if index > 0:
        prev = tokens[index - 1]
    return render_template(
        'token.html',
        token=token,
        prev=prev,
        next=next
    )

@bp.route('/collection/<collection_id>/<token_id>/<action>')
def update_token(collection_id, token_id, action):
    collection = Collection.query.get(collection_id)
    if not collection:
        flash('That collection does not exist!', 'warning')
        return redirect(url_for('collection.index'))
    token = Token.query.filter(
        Token.token_id == token_id,
        Token.collection_id == collection_id
    ).first()
    if not token:
        flash('That token does not exist for that collection!', 'warning')
        return redirect(url_for('collection.show', collection_id=collection_id))
    if current_user.is_anonymous:
        flash('Must be authenticated.', 'warning')
        return redirect(url_for('collection.index'))
    if not collection.user_can_access(current_user.id):
        flash('You are not allowed to access that collection.', 'warning')
        return redirect(url_for('collection.index'))
    if action == 'approve':
        token.rejected = False
        token.approved = True
        token.reject_reason = None
        db.session.commit()
        flash(f'Token was approved!', 'success')
    elif action == 'reject':
        if not request.args.get('reason'):
            flash('You need to specify a reason for rejection.', 'warning')
            return redirect(url_for('collection.show_token', collection_id=collection_id, token_id=token.token_id))
        token.rejected = True
        token.approved = False
        token.reject_reason = request.args.get('reason')
        db.session.commit()
        flash(f'Token was rejected!', 'error')
    else:
        flash('Unknown action.', 'warning')
    next = collection.get_tokens().first()
    return redirect(url_for('collection.show_token', collection_id=collection_id, token_id=next.token_id))

metachecker/templates/about.html
<!DOCTYPE html>
<html>
  {% include 'includes/head.html' %}
  <body>
  {% include 'includes/navbar.html' %}
  <section class="section">
    <div class="container">
        <div class="screen" style="padding-top:1em;">
          <p>
            This service is a simple way for NFT project owners to collaborate on the metadata of their collections before applying to contracts on networks. It came about after issues with my own project, where my artist was compiling metadata and images locally, uploading to IPFS, and providing me with a new hash. I would take his IPFS hash, perform <code>curl</code> checks in my Terminal, pipe outputs to <code>jq</code>, and <code>diff</code> the results. This QA process was all very manual, error prone, and haphazard. It obviously needed to improve.</br>
          </p>
        </br>
          <p>
            I was inspired by the <a href="https://twitter.com/tubbycatsnft/" target="_blank">Tubby Cats NFT</a> project where they used a tool that allowed them to collaborate in a shared dashboard to review artwork and metadata, performing QA testing.
          </p>
        </br>
          <p>I thought I would develop something for my own project's needs and it wouldn't hurt if others could use it as well.</p>
        </div>
    </div>
  </section>
  {% include 'includes/footer.html' %}
  </body>
</html>

metachecker/templates/collection.html
{% set total_tokens = collection.end_token_id + 1 - collection.start_token_id %}
<!DOCTYPE html>
<html>
  {% include 'includes/head.html' %}
  <body>
  {% include 'includes/navbar.html' %}
  <section class="section">
    <div class="container has-text-centered">
      <h1 class="title">{{ collection.title }}</h1>
      <p class="subtitle pt-2">{{ collection.metadata_uri }}</p>
      <nav class="level">
        <div class="level-item">
          <div>
            <p class="heading">Tokens</p>
            <p class="title">{{ total_tokens }}</p>
            {% if (collection.tokens | length) < total_tokens %}
            <p>{{ collection.tokens | length }} tokens scanned</p>
            {% endif %}
          </div>
        </div>
        <div class="level-item">
          <div>
            <p class="heading">Collaborators</p>
            <p class="title">{{ (collection.accesses | length) + 1 }}</p>
          </div>
        </div>
        <div class="level-item">
          <div>
            <p class="heading">Rejected</p>
            <p class="title">
              {% set rejected = collection.get_tokens(rejected=True) %}
              {% if rejected.count() %}
              <a href="{{ url_for('collection.show_token', collection_id=collection.id, token_id=rejected.first().token_id) }}?show=rejected" up-target=".container" up-transition="cross-fade">
                {{ rejected.count() }}
              </a>
              {% else %}
              0
              {% endif %}
            </p>
          </div>
        </div>
        <div class="level-item">
          <div>
            <p class="heading">Approved</p>
            <p class="title">
              {% set approved = collection.get_tokens(approved=True) %}
              {% if approved.count() %}
              <a href="{{ url_for('collection.show_token', collection_id=collection.id, token_id=approved.first().token_id) }}?show=approved" up-target=".container" up-transition="cross-fade">
                {{ approved.count() }}
              </a>
              {% else %}
              0
              {% endif %}
            </p>
          </div>
        </div>
        <div class="level-item">
          <div>
            <p class="heading">Unreviewed</p>
            <p class="title">
              {% set unreviewed = collection.get_tokens() %}
              {% if unreviewed.count() %}
              <a href="{{ url_for('collection.show_token', collection_id=collection.id, token_id=unreviewed.first().token_id) }}" up-target=".container" up-transition="cross-fade">
                {{ unreviewed.count() }}
              </a>
              {% else %}
              0
              {% endif %}
            </p>
          </div>
        </div>
      </nav>
      <div class="columns">
        <div class="column">
          <form method="GET" style="width:50%;margin:auto;padding-top:2em;" enctype="multipart/form-data" class="site-form" action="{{ url_for('collection.add_collaborator', collection_id=collection.id) }}">
            <div class="field">
              <div class="control">
                <input class="input" type="text" placeholder="Collaborator wallet address" name="address">
              </div>
            </div>
            <button class="button is-success" up-follow=".container" up-transition="cross-fade">Add Collaborator</button>
          </form>
          <div class="pt-4">
            <p class="subtitle pt-4">Collaborators</p>
            <ul>
              <li><strong>{{ collection.user.public_address }}</strong></li>
            {% for access in collection.accesses %}
              <li>{{ access.public_address }}</li>
            {% endfor %}
            </ul>
          </div>
        </div>
      </div>
      <div class="tokenPreviews has-text-centered">
        <p class="subtitle">Tokens</p>
        {% set tokens = collection.get_tokens(start=start, end=end) %}
        {% for _batch in tokens.all() | batch(4) %}
        <div class="columns">
          {% for token in _batch %}
          <div class="card column {% if token.approved %}approvedCard{% elif token.rejected %}rejectedCard{% endif %}">
            <div class="card-image">
              <figure class="image">
                <a href="{{ url_for('collection.show_token', collection_id=collection.id, token_id=token.token_id) }}" up-target=".container" up-preload>
                  <img src="/static/img/loading.gif" width=40 class="tokenPreview previewPreload" id="tokenPreview-{{ token.id }}" up-data="{{ token.id }}">
                </a>
              </figure>
            </div>
          </div>
          {% endfor %}
        </div>
        {% endfor %}
        <p>Showing token IDs #{{ start }} - #{{ end }}</p>
        {% if end > (collection.start_token_id + 16) %}
          <a href="?start={{ start - 16 }}&end={{ end - 16 }}" up-push up-target=".tokenPreviews" up-preload class="button is-info is-light">Previous Batch</a>
        {% endif %}

        {% if end < collection.end_token_id %}
        <a href="?start={{ end }}&end={{ end + 16 }}" up-push up-target=".tokenPreviews" up-preload class="button is-info is-light">Next Batch</a>
        {% endif %}
      </div>
    </div>
  </section>
  {% include 'includes/footer.html' %}
  </body>
</html>

metachecker/templates/index.html
<!DOCTYPE html>
<html>
  {% include 'includes/head.html' %}
  <body>
  {% include 'includes/navbar.html' %}
  <section class="section">
    <div class="container has-text-centered">
      {% if collections %}
      <table class="table screen-lg">
        <thead>
          <tr>
            <th>Title</th>
            <th>Metadata URI</th>
            <th>Creation Date</th>
          </tr>
        </thead>
        <tbody>
          {% for collection in collections %}
          <tr>
            <td><a href="{{ url_for('collection.show', collection_id=collection.id) }}" up-target=".container" up-transition="cross-fade">{{ collection.title }}</a></td>
            <td>{{ collection.metadata_uri }}</td>
            <td>{{ collection.create_date | humanize }}</td>
          </tr>
          {% endfor %}
        </tbody>
        </table>
      {% else %}
        <div class="notification is-secondary has-text-centered">
          <p>You're not part of any collections yet</p>
        </div>
      {% endif %}
    </div>
  </section>
  {% include 'includes/footer.html' %}
  </body>
</html>

metachecker/templates/new.html
<!DOCTYPE html>
<html>
  {% include 'includes/head.html' %}
  <body>
  {% include 'includes/navbar.html' %}
  <section class="section">
    <div class="container">
      <div class="screen">
      <form method="POST" enctype="multipart/form-data" class="site-form" action="{{ url_for('collection.new') }}" style="padding-top:1.5em;">
        <div class="field">
          <label class="label">Title</label>
          <div class="control">
            <input class="input" type="text" placeholder="Title of your collection" name="title">
          </div>
        </div>
        <div class="field">
          <label class="label">Base Metadata URI</label>
          <div class="control">
            <input class="input" type="text" placeholder="https://gateway.pinata.cloud/ipfs/xxxxxxxxxxxxxxx/" name="metadata_uri">
          </div>
        </div>
        <div class="field">
          <label class="label">Start Token ID</label>
          <div class="control">
            <input class="input" type="number" min=0 placeholder="1" name="start_token_id">
          </div>
        </div>
        <div class="field">
          <label class="label">End Token ID</label>
          <div class="control">
            <input class="input" type="number" min=0 placeholder="10000" name="end_token_id">
          </div>
        </div>
        <div class="field is-grouped">
          <div class="control">
            <button class="button is-primary" up-follow=".container">Submit</button>
          </div>
        </div>
      </form>
      </div>
    </div>
  </section>
  {% include 'includes/footer.html' %}
  </body>
</html>

metachecker/templates/publish.html
<!DOCTYPE html>
<html>
  {% include 'includes/head.html' %}
  <body>
  <section class="section">
    <div class="container">
      {% include 'includes/navbar.html' %}

      <div class="screen">
      <form method="POST" enctype="multipart/form-data" class="site-form" id="memeUpload" action="{{ url_for('meme.publish') }}" style="padding-top:1.5em;">
        <div class="field">
          <label class="label">File</label>
          <div class="control">
            <input class="filestyle" id="file" name="file" required type="file">
          </div>
        </div>

        <div class="field">
          <label class="label">Poster Address</label>
          <div class="control">
            <p>{{ current_user.public_address }}</p>
          </div>
        </div>

        <div class="field">
          <label class="label">Title</label>
          <div class="control">
            <input class="input" type="text" placeholder="Title of your meme" name="title">
          </div>
        </div>

        <div class="field">
          <label class="label">Description</label>
          <div class="control">
            <textarea class="textarea" placeholder="Description..." name="description"></textarea>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <label class="checkbox">
              <input type="checkbox">
              I agree to support the ongoing funding of exploratory meme missions
            </label>
          </div>
        </div>

        <div class="field is-grouped">
          <div class="control">
            <button class="button is-primary" up-follow=".container">Submit</button>
          </div>
        </div>
      </form>
      </div>
    </div>
  </section>
  </body>
</html>

metachecker/templates/token.html
<!DOCTYPE html>
<html>
  {% include 'includes/head.html' %}
  <body>
  {% include 'includes/navbar.html' %}
  <section class="section">
    <div class="container has-text-centered">

      <nav class="breadcrumb is-centered" aria-label="breadcrumbs">
        <ul>
          <li><a href="{{ url_for('collection.index') }}" up-follow up-target=".container" up-preload up-transition="cross-fade">Home</a></li>
          <li><a href="{{ url_for('collection.show', collection_id=token.collection.id) }}" up-follow up-target=".container" up-preload up-transition="cross-fade">{{ token.collection.title }}</a></li>
          <li class="is-active"><a aria-current="page">#{{ token.token_id }}</a></li>
        </ul>
      </nav>
      <div class="content">

        <div class="columns">
          <div class="column">
            {% if token.token_id > token.collection.start_token_id and prev %}
            <a class="button" href="{{ url_for('collection.show_token', collection_id=token.collection.id, token_id=prev.token_id) }}{{ request.args | fix_args }}" up-follow up-target=".container" up-preload up-transition="move-right"><- #{{ prev.token_id }}</a>
            {% endif %}
          </div>
          {% set _next = token.collection.get_tokens().first() %}
          {% if _next and token.id != _next.id %}
          <div class="column">
            <a class="button is-info" href="{{ url_for('collection.show_token', collection_id=token.collection.id, token_id=_next.token_id) }}" up-follow up-target=".container" up-preload up-transition="cross-fade">Unreviewed #{{ _next.token_id }}</a>
          </div>
          {% endif %}
          <div class="column">
            {% if token.token_id < token.collection.end_token_id and next %}
            <a class="button" href="{{ url_for('collection.show_token', collection_id=token.collection.id, token_id=next.token_id) }}{{ request.args | fix_args }}" up-follow up-target=".container" up-preload up-transition="move-left">#{{ next.token_id }} -></a>
            {% endif %}
          </div>
        </div>

        {% if token.approved %}
        <div class="notification is-success">
          <span class="tokenStatus"><img src="/static/img/approved.svg" width=20> Approved.</span>
        </div>
        {% elif token.rejected %}
        <div class="notification is-danger">
          <span class="tokenStatus"><img src="/static/img/rejected.svg" width=20> Rejected. Reason: <strong>{{ token.reject_reason }}</strong></span>
        </div>
        {% endif %}

        <div class="columns">
          <div class="column">
            <h1 class="title" id="tokenTitle" up-data="{{ token.id }}"><img src="/static/img/loading.gif" width=50></h1>
            <p class="block" id="tokenDescription"></p>
            <div class="block"></div>
            <ol id="tokenTraits"></ol>
          </div>
          <div class="column">
            <img src="/static/img/loading.gif" id="tokenImage" />
          </div>
        </div>

        {% if not token.approved and not token.rejected %}
        <div class="columns" id="updateButtons">
          <div class="column">
            <a href="{{ url_for('collection.update_token', collection_id=token.collection.id, token_id=token.token_id, action='approve') }}" class="button is-success" style="width:100%;" up-follow=".container" up-transition="cross-fade">Approve</a>
          </div>
          <div class="column">
            <form method="GET" enctype="multipart/form-data" class="site-form" action="{{ url_for('collection.update_token', collection_id=token.collection.id, token_id=token.token_id, action='reject') }}">
              <button class="button is-danger" style="width:100%;" up-follow=".container" up-transition="cross-fade">Reject</button>
              <div class="field">
                <div class="control">
                  <input class="input" type="text" placeholder="reject reason..." name="reason">
                </div>
              </div>
            </form>
          </div>
        </div>
        {% endif %}

      </div>
    </div>

  </section>
  {% include 'includes/footer.html' %}
  </body>
</html>