metachecker/routes/meta.py
import requests
from flask import Blueprint, render_template
from flask import redirect, url_for
from flask_login import logout_user, login_required

from metachecker import config


bp = Blueprint('meta', 'meta')


@bp.route('/about')
def about():
    return render_template('about.html')


@bp.route('/disconnect')
def disconnect():
    logout_user()
    return redirect(url_for('collection.index'))

@bp.route('/ipfs/<path:path>')
@login_required
def load_ipfs(path):
    ipfs_uri = f'{config.IPFS_SERVER}/ipfs/{path}'
    res = requests.get(ipfs_uri, timeout=60)
    return res.content

metachecker/templates/includes/collection_card.html
{# expects collection var #}
<div class="card">
  <div class="card-image">
    <figure class="image">
      <a href="#">
        {{ collection.title }}
      </a>
    </figure>
  </div>
  <div class="card-content">
    <div class="media">
      <div class="media-left">
      </div>
      <div class="media-content">
        <p class="title is-4">{{ collection.title }}</p>
        <p class="subtitle is-6">
          <a href="#">{{ collection.metadata_uri }}</a>
          <a href="#" target="_blank">#</a>
        </p>
      </div>
    </div>

    <div class="content">
      <time datetime="2016-1-1">{{ collection.create_date.strftime('%H:%M UTC - %d %b %Y') }}</time>
    </div>
  </div>
</div>

metachecker/templates/includes/footer.html
<footer style="margin: 0 auto; width: 100%; text-align: center; padding: 4em 0 1em 0;">
  <p>Made by <a href="https://lzahq.tech" target="_blank">@lza_menace</a> of <a href="https://twitter.com/art101nft" target="_blank">@Art101NFT</a>.</p>
  <p>Logo made by <a href="https://twitter.com/BigPeachNFTs">@BigPeachNFTs</a>.</p>
</footer>


{% include 'includes/scripts.html' %}

metachecker/templates/includes/head.html
<head>
  <title>metachecker</title>
  <meta property="og:description" content="NFT project metadata collaboration and review platform.">
  <meta property="og:image" content="https://metachecker.io/static/img/logo_large.png">
  <meta property="og:title" content="metachecker">
  <meta name="twitter:card" content="summary">
  <meta name="twitter:site" content="@lza_menace">
  <meta name="twitter:title" content="metachecker">
  <meta name="twitter:description" content="NFT project metadata collaboration and review platform.">
  <meta name="twitter:creator" content="@lza_menace">
  <meta name="twitter:image" content="https://metachecker.io/static/img/logo_large.png">
  <meta name="twitter:domain" content="https://metachecker.io">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="/static/css/vendor/unpoly-2.5.0.min.css">
  <link rel="stylesheet" href="/static/css/bulma.min.css">
  <!-- <link rel="stylesheet" href="/static/css/bulma.css.map"> -->
  <link rel="stylesheet" href="/static/css/vendor/noty-relax.css" />
  <link rel="stylesheet" href="/static/css/vendor/noty.css" />
  <link rel="stylesheet" href="/static/css/custom.css" />
  <link rel="icon" type="image/x-icon" href="/static/favicon.ico">
</head>

metachecker/templates/includes/navbar.html
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/" up-target=".container" up-transition="cross-fade">
      <!-- <h1 class="title"><img src="/static/img/logo_white.png" height="120"></h1> -->
      <img src="/static/img/logo_white.png" height="120">
    </a>
  </div>
  <div class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href="{{ url_for('meta.about') }}" up-target=".container" up-transition="cross-fade">About</a>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          {% if current_user.is_authenticated %}
            <a class="button is-danger is-light" href="{{ url_for('meta.disconnect') }}">Disconnect</a>
            <a class="button is-primary is-light" href="{{ url_for('collection.new') }}">New Collection</a>
          {% else %}
            <a class="button is-link is-light" id="metamaskConnect" onclick="onboardMetaMask();">Connect</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</nav>

metachecker/templates/includes/scripts.html
<script src="/static/js/vendor/noty-3.2.0.js"></script>
<script src="/static/js/vendor/unpoly-2.5.0.min.js"></script>
<script src="/static/js/main.js"></script>

{% if current_user.is_anonymous %}
{% include 'includes/web3.html' %}
{% endif %}

{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% if category == None %}{% set category = 'info' %}{% endif %}
      {% for category, message in messages %}
        <div class="notyBox" up-data='{"message": "{{ message }}", "category": "{{ category }}"}'></div>
      {% endfor %}
  {% endif %}
{% endwith %}

metachecker/templates/includes/token_card.html
{# expects token and collection vars #}
{% set data = token.get_metadata_dict() %}
{% set token_url = url_for('collection.show_token', collection_id=collection.id, token_id=token.token_id) %}
<div class="card">
  <div class="card-image">
    <figure class="image">
      <a href="{{ token_url }}" up-follow up-preload up-target=".container">
        <img alt="{{ data.name }}" src="https://bulma.io/images/placeholders/128x128.png" width="200px" class="img-fluid" />
        <!-- <img alt="{{ data.name }}" src="{{ data.image | convert_ipfs_uri }}" width="200px" class="img-fluid" /> -->
      </a>
    </figure>
  </div>
  <div class="card-content">
    <div class="media">
      <div class="media-content">
        <p class="title is-4"><a href="{{ token_url }}" up-follow up-preload up-target=".container">{{ data.name }}</a></p>
        <div class="tags">
        {% for attrib in data.attributes %}
          <span class="tag is-light">{{ attrib.trait_type }}: {{ attrib.value }}</span>
        {% endfor %}
        </div>
      </div>
    </div>
    <!-- <div class="content">
      <time datetime="2016-1-1">{{ collection.create_date.strftime('%H:%M UTC - %d %b %Y') }}</time>
      <div class="columns mt-2">
        <div class="column">
          <a class="button is-success" href="#">Approve</a>
        </div>
        <div class="column">
          <a class="button is-danger" href="#">Deny</a>
        </div>
      </div>
    </div> -->
  </div>
</div>

metachecker/templates/includes/web3.html
<script src="/static/js/vendor/web3-1.3.6.min.js"></script>
<script src="/static/js/vendor/metamask-onboarding-1.0.1.bundle.js"></script>
<script type="text/javascript">

  window.addEventListener('DOMContentLoaded', () => {
    // Arm connect button
    onboardMetaMask();

    // Detect account changes in MetaMask
    if (MetaMaskOnboarding.isMetaMaskInstalled()) {
      window.ethereum.on('accountsChanged', (newAccounts) => {
        window.location.href = '/disconnect';
      });
    }
  })

  async function getMetamaskAccount() {
    const accounts = await window.ethereum.request({
      method: 'eth_requestAccounts',
    });
    const account = accounts[0];
    return account
  }

  async function getSignedData(publicAddress, jsonData) {
    const signedData = await window.ethereum.request({
      method: 'eth_signTypedData_v3',
      params: [publicAddress, JSON.stringify(jsonData)]
    });
    console.log(signedData);
    return signedData
  }

  async function onboardMetaMask(){
    const onboarding = new MetaMaskOnboarding();
    const onboardButton = document.getElementById('metamaskConnect');
    let accounts;
    let nonce = 0;

    if (!onboardButton) {
      return false;
    }

    onboardButton.onclick = async () => {
      if (!MetaMaskOnboarding.isMetaMaskInstalled()) {
        onboardButton.onclick = () => {
          onboardButton.classList.add('is-loading');
          onboardButton.disabled = true;
          onboarding.startOnboarding();
        };
      } else if (accounts && accounts.length > 0) {
        onboardButton.classList.remove('is-loading');
        onboardButton.disabled = false;
        onboarding.stopOnboarding();
      } else {
        try {
          onboardButton.classList.add('is-loading');
          onboardButton.disabled = true;
          let userExists;
          const allAccounts = await window.ethereum.request({
            method: 'eth_requestAccounts',
          });
          await fetch('/api/v1/user_exists?public_address=' + allAccounts[0])
            .then((resp) => resp.json())
            .then(function(data) {
                if (!data['success']) {
                  console.log('error checking user_exists!')
                  return
                }
                console.log(data);
                nonce = data['nonce'];
            })

          const msg = `Authentication request from metachecker app!

Verifying message with nonce ${nonce}`
          const signedData = await window.ethereum.request({
            method: 'personal_sign',
            params: [msg, allAccounts[0]]
          });
          console.log(`Signing data with msg "${msg}", address "${allAccounts[0]}", signed data: ${signedData}`)

          await fetch('/api/v1/authenticate/metamask', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json;charset=utf-8'
            },
            body: JSON.stringify({
              'signed_data': signedData,
              'public_address': allAccounts[0],
              'nonce': nonce,
              'message': msg,
            })
          })
            .then((resp) => resp.json())
            .then(function(data) {
                console.log(data);
                if (data['success']) {
                  window.location.href = '/';
                }
            })
        } catch(e) {
          console.log(e);
          onboardButton.classList.remove('is-loading');
        }
      }
    };

  };
</script>